/**
 * This file is auto-generated by the generate-colors.js script.
 * Do not edit this file directly.
 */

export const colors = {
	light: {
		background: "hsl(0, 0%, 100%)",
		foreground: "hsl(30, 8%, 7%)",
		card: "hsl(0, 0%, 100%)",
		cardForeground: "hsl(30, 8%, 7%)",
		popover: "hsl(0, 0%, 100%)",
		popoverForeground: "hsl(30, 8%, 7%)",
		primary: "hsl(65, 21%, 54%)",
		primaryForeground: "hsl(0, 0%, 100%)",
		secondary: "hsl(65, 21%, 95%)",
		secondaryForeground: "hsl(30, 8%, 7%)",
		muted: "hsl(0, 0%, 97%)",
		mutedForeground: "hsl(0, 0%, 44%)",
		accent: "hsl(224, 71%, 83%)",
		accentForeground: "hsl(30, 8%, 7%)",
		destructive: "hsl(0, 80%, 57%)",
		destructiveForeground: "hsl(0, 0%, 100%)",
		border: "hsl(0, 0%, 91%)",
		input: "hsl(0, 0%, 91%)",
		ring: "hsl(65, 21%, 54%)",
	},
};
